# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: 
      - master
      - all-in-packages
  pull_request:
    branches: 
      - master
      - all-in-packages

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 13.x]

    steps:
    - uses: actions/checkout@v1
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: bootstrap
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test
